### ISSUE TITLE
Build instructions are out of date

### ISSUE THREAD

**Issue by mruegenberg** [jeremyletang/rgtk#181]
The readme tells me to use `./configure`, but there's neither a configure file nor a file for autoconf to generate one from.

Using `cargo build` seems to work (though I get a probably unrelated build error about core::marker::Sized not being implemented for str, most likely because I'm using the newest nightly).

**Comment by GuillaumeGomez** [comment]
I haven't finished to update rgtk to the last rustc version. It will be finished in the evening (I hope).

For the configure file, you can find it [here](https://github.com/GuillaumeGomez/rgtk/blob/19b3a7021731e2601337ce36c1073d9c26a7a2a0/configure). It's very weird that we did remove it...
@jeremyletang: configure executable is missing, do you know why ?

**Comment by jeremyletang** [comment]
`./configure` is no more needed with cargo, it was an `autoconf` generated file who generate the makefile ( in a time with no cargo package manager ). We just need to remove it from the read me.

**Comment by GuillaumeGomez** [comment]
I updated the readme file 29ee05b6840a099e0fa7f369e84e81bf462efe50.
