### ISSUE TITLE
gdk_keyval_name missing

### ISSUE THREAD

**Issue by ptersilie** [jeremyletang/rgtk#203]
I wanted to catch keypresses on a DrawingArea and then convert the key value to it's corresponding character to be able to draw it onto the canvas. Unfortunately the ffi is missing the gtk method "gdk_keyval_name"[1].

Is this hard to add? If someone could give me a tip on how to do this I'd be happy to contribute this myself in form of a pull request. :)

[1] https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keyval-name

**Comment by GuillaumeGomez** [comment]
Nothing very hard, don't worry. I give you a little guide :

- First, go to the [ffi file]https://github.com/jeremyletang/rgtk/blob/master/src/gdk/ffi.rs) and add the missing function next to its corresponding functions.
- Then add the declaration of the function in the good file. In this case, I think you'll need to create a new one (key.rs ?).
- Don't forget to add the new file created in [here](https://github.com/jeremyletang/rgtk/blob/master/src/gdk/widgets/mod.rs) to reexport it.

If you have any question, please ask.

**Comment by ptersilie** [comment]
Thanks. That really doesn't sound that hard. I already started hacking on that and I feel like I actually know what I'm doing ;). Unfortunately I can't seem to be able to build rgtk (even without my changes). I'm getting this error:

```
src/cairo/ffi.rs:82:1: 82:52 error: conflicting implementations for trait `core::marker::Send` [E0119]
src/cairo/ffi.rs:82 unsafe impl Send for *mut cairo_rectangle_list_t {}
```

I think I'm on the current version of rust (4db0b3246 2015-02-25) and cargo (5773064 2015-02-25), so I'm not sure what causes that error. Any ideas?

**Comment by GuillaumeGomez** [comment]
It has been reported on PR #199. I don't have time to take a look today. I hope I'll have tomorrow...

**Comment by ptersilie** [comment]
Thanks! I pulled the update. Building works now. Will start working on the keyval stuff tomorrow. :)

**Comment by GuillaumeGomez** [comment]
Nice !

**Comment by ptersilie** [comment]
Added pull request #207
