### ISSUE TITLE
GTK version not being detected correctly

### ISSUE THREAD

**Issue by oakes** [jeremyletang/rgtk#214]
I use Ubuntu, and I have `features = ["GTK_3_10"]` in my Cargo.toml. When I attempt to use `gtk::Stack`, which requires 3.10, I get a linker error `undefined reference to cast_GtkStack`. I knew this was one of the functions defined in gtk_glue.c, so I manually commented out the `if defined` directive that surrounds it, and it worked. It seems that the features specified in the Cargo.toml aren't making it to gtk_glue.c.

**Comment by oakes** [comment]
Ah, I need to manually set the `GTK_VERSION` environment variable.

**Comment by oakes** [comment]
I need to reopen this, because even when I `export GTK_VERSION=GTK_3_10` and rebuilding, I get the linker error. How do I get the version to be detected when gtk_glue.c is compiled?

**Comment by gkoz** [comment]
`GTK_VERSION` is no more. #206 removes it from the readme. #215 should fix this issues.
