### ISSUE TITLE
Rust nightly changes

### ISSUE THREAD

**Issue by gkoz** [jeremyletang/rgtk#249]
The trivial casts lint is upon us. Whoever starts fixing the warnings can leave a message here.

**Comment by gkoz** [comment]
It seems the trivial_numeric_casts lint may become allow by default.
https://github.com/rust-lang/rfcs/issues/1020

**Comment by GuillaumeGomez** [comment]
Oh come on ! They're can't be serious ! It was a pain in the pass to update some of my libs yesterday and they say I did it for nothing ? Seriously... Well, luckily, I didn't start doing it on rgtk...

**Comment by gkoz** [comment]
What's worse, in cases of `i64 as c_long` (which can be `i32` or `i64` on different platforms) and vice versa, removing the cast would be incorrect.

**Comment by GuillaumeGomez** [comment]
For that, I totally agree. But I was thinking that they somehow found a way to cast automatically if this is a c_type to waiting type. Seemed logical to me...
